version: '3'

server:
  command: "php worker.php"

http:
  address: 0.0.0.0:8080
  env:
    - XDEBUG_SESSION: 1
  pool:
    debug: true
    num_workers: 1

# do not use development mode in production
logs:
  level: debug
  mode: development
